# -*- coding: utf-8 -*-
"""LAB_3_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCH0hVmNadL9FXOJT0HSoBmBmeqHyX1v
"""

#Импорт файла (метод можно поменять)
from google.colab import drive
import os

drive.mount('/content/gdrive')

os.chdir(r'/content/gdrive/MyDrive/Data/LAB_3_8')
os.listdir()

import numpy as np
from numpy import sqrt
import pandas as pd
import matplotlib.pyplot as plt

#Распаковка и преобразование основных данных
df = pd.read_csv('LAB_3_8_base.csv')
df = df.replace(',', '.', regex=True)
df[['hx+','hx-','hy+','hy-','kx','ky','length']] = df[['hx+','hx-','hy+','hy-','kx','ky','length']].astype(float)

#Распаковка и преобразование констант
df_const = pd.read_csv('LAB_3_8_constants.csv')
df_const.set_index('Name', inplace=True)
df_const = df_const.replace(',', '.', regex=True)
df_const[['Constants', 'Error']] = df_const[['Constants', 'Error']].astype(float)

#Введение μ0
mu0 = 4 * np.pi * (10 ** -7)

df_const

#Подсчёт hx и hy
df['hx'] = df[['hx+', 'hx-']].mean(axis=1)
df['hy'] = df[['hy+', 'hy-']].mean(axis=1)

#Подсчёт m_h и m_b
m_h = ((df_const.loc['N1', 'Constants'])
      / (df_const.loc['R_e', 'Constants'] * df_const.loc['l1', 'Constants']))
dm_h = sqrt(
    (
        df_const.loc['N1', 'Error']
        / (df_const.loc['l1', 'Constants'] * df_const.loc['R_e', 'Constants'])
    ) ** 2
    + (
        (df_const.loc['N1', 'Constants'] * df_const.loc['l1', 'Error'])
        / (df_const.loc['R_e', 'Constants'] * (df_const.loc['l1', 'Constants'] ** 2))
    ) ** 2
    + (
        (df_const.loc['N1', 'Constants'] * df_const.loc['R_e', 'Error'])
        / (df_const.loc['l1', 'Constants'] * (df_const.loc['R_e', 'Constants']) ** 2)
    ) ** 2
)
S0 = np.pi * (df_const['Constants']['d'] ** 2) / 4
m_b = (df_const['Constants']['R'] * df_const['Constants']['C']) / (df_const['Constants']['N'] * S0)
dm_b = 4 * sqrt(
    (
        df_const.loc['C', 'Constants'] * df_const.loc['R', 'Error']
        / (df_const.loc['N', 'Constants'] * (df_const.loc['d', 'Constants'] ** 2))
    ) ** 2
    + (
        (df_const.loc['R', 'Constants'] * df_const.loc['C', 'Error'])
        / (df_const.loc['N', 'Constants'] * (df_const.loc['d', 'Constants'] ** 2))
    ) ** 2
    + (
        (2 * df_const.loc['R', 'Constants'] * df_const.loc['C', 'Constants'] * df_const.loc['d', 'Error'])
         / (df_const.loc['N', 'Constants'] * (df_const.loc['d', 'Constants'] ** 3))
    ) ** 2
) / np.pi
m_h

#Подсчёт H и dH
df['H'] = df['kx'] * df['hx'] * m_h
df['H_error'] = df['kx'] * sqrt((0.1 * m_h) ** 2 + (df['hx'] * dm_h) ** 2)

#Подсчёт В и dB
df['B'] = m_b * df['ky'] * df['hy']
df['B_error'] = df['ky'] * sqrt((0.1 * m_b) ** 2 + (df['hy'] * dm_b) ** 2)

df['mu'] = df['B'] / (mu0 * df['H'])
df['mu_error'] = sqrt(
    (df['B_error'] / df['H']) ** 2
    + (df['B'] * df['H_error'] / (df['H'] ** 2)) ** 2
) / mu0
df

#Итогое форматирование перед постройкой графиков
df = df.sort_values(['length', 'H'])

#Построение кривых намагничивания
plt.title('Основные кривые намагничивания')
plt.xlabel('Напряжённость магнитного поля Н, А/м', fontsize=8.)
plt.ylabel('Магнитная индукция B, Тл', fontsize=8.)

plt.xlim(800, 6500)
plt.ylim(0, 2)

plt.plot(df.loc[df['length'] == 1, 'H'], df.loc[df['length'] == 1, 'B'], '-b', marker='o', label='Длинный образец')
plt.plot(df.loc[df['length'] == 0, 'H'], df.loc[df['length'] == 0, 'B'], '-r', marker='x', label='Короткий образец')
plt.errorbar(
    df.loc[df['length'] == 1, 'H'], df.loc[df['length'] == 1, 'B'],
    df.loc[df['length'] == 1, 'B_error'], df.loc[df['length'] == 1, 'H_error'],
    '-b', capsize = 2, linestyle = ''
    )
plt.errorbar(
    df.loc[df['length'] == 0, 'H'], df.loc[df['length'] == 0, 'B'],
    df.loc[df['length'] == 0, 'B_error'], df.loc[df['length'] == 0, 'H_error'],
    '-r', capsize = 2, linestyle = ''
    )

plt.grid(axis = 'x')
plt.legend(loc = 'best')
plt.grid(alpha = 0.5)
plt.savefig('Основные_кривые_намагничивания.png')
plt.show()

#Зависимость проницаемости от напряжённости
plt.title('Зависимость магнитной проницаемости μ от\n напряжённости магнитного поля H')
plt.xlabel('Напряжённость магнитного поля Н, А/м', fontsize=8.)
plt.ylabel('Магнитная проницаемость μ', fontsize=8.)

plt.xlim(800, 6500)
plt.ylim(0, 500)

plt.plot(df.loc[df['length'] == 1, 'H'], df.loc[df['length'] == 1, 'mu'], '-b', marker='o', label='Длинный образец')
plt.plot(df.loc[df['length'] == 0,'H'], df.loc[df['length'] == 0, 'mu'], '-r', marker='o', label='Короткий образец')
plt.errorbar(
    df.loc[df['length'] == 1, 'H'], df.loc[df['length'] == 1, 'mu'],
    df.loc[df['length'] == 1, 'mu_error'], df.loc[df['length'] == 1, 'H_error'],
    '-b', capsize = 2, linestyle = ''
    )
plt.errorbar(
    df.loc[df['length'] == 0, 'H'], df.loc[df['length'] == 0, 'mu'],
    df.loc[df['length'] == 0, 'mu_error'], df.loc[df['length'] == 0, 'H_error'],
    '-r', capsize = 2, linestyle = ''
    )

plt.grid(axis = 'x')
plt.legend(loc = 'best')
plt.grid(alpha = 0.5)
plt.savefig('Зависимость_магнитной_проницаемости_μ_от_напряжённости_магнитного_поля_H.png')
plt.show()

#Распаковка данных для задания 2
df2 = pd.read_csv('LAB_3_8_base_task2.csv')
df2 = df2.replace(',', '.', regex=True)
df2[['hy+', 'hy-', 'hx', 'ky', 'kx', 'length']] = df2[['hy+', 'hy-', 'hx', 'ky', 'kx', 'length']].astype(float)
df2

#Подсчёт H и dH
df2['H'] = df2['kx'] * df2['hx'] * m_h
df2['H_error'] = df2['kx'] * sqrt(
    (0.1 * m_h) ** 2
    + (df2['hx'] * dm_h) ** 2
)

#Подсчёт B- и dB-
df2['B-'] = df2['ky'] * df2['hy-'] * m_b
df2['B-_error'] = df2['ky'] * sqrt(
    (0.1 * m_b) ** 2
    + (df2['hy-'] * dm_b) ** 2
)

#Подсчёт B+ и dB+
df2['B+'] = df2['ky'] * df2['hy+'] * m_b
df2['B+_error'] = df2['ky'] * sqrt(
    (0.1 * m_b) ** 2
    + (df2['hy+'] * dm_b) ** 2
)
df2

#Подсчёт площадей
S1 = (
    (df2.loc[df2['length'] == 1, 'hx'].iloc[0] - df2.loc[df2['length'] == 1, 'hx'].iloc[1])
    * (df2.loc[df2['length'] == 1, 'hy+'].sum() - df2.loc[df2['length'] == 1, 'hy-'].sum())
)
dS1 = sqrt(
    (0.1 * (df2.loc[df2['length'] == 1, 'hy+'].sum() - df2.loc[df2['length'] == 1, 'hy-'].sum())) ** 2
    + (8 * 0.1 * df2.loc[df2['length'] == 1, 'kx'].iloc[0] * (df2.loc[df2['length'] == 1, 'hx'].iloc[0] - df2.loc[df2['length'] == 1, 'hx'].iloc[1])) ** 2
)


S2 = (
    (df2.loc[df2['length'] == 0, 'hx'].iloc[0] - df2.loc[df2['length'] == 0, 'hx'].iloc[1])
    * (df2.loc[df2['length'] == 0, 'hy+'].sum() - df2.loc[df2['length'] == 0, 'hy-'].sum())
)
dS2 = sqrt(
    (0.1 * (df2.loc[df2['length'] == 0, 'hy+'].sum() - df2.loc[df2['length'] == 0, 'hy-'].sum())) ** 2
    + (8 * 0.1 * df2.loc[df2['length'] == 1, 'kx'].iloc[0] * (df2.loc[df2['length'] == 0, 'hx'].iloc[0] - df2.loc[df2['length'] == 0, 'hx'].iloc[1])) ** 2
)
S1

#Подсчёт энергий и мощностей
W1 = S1 * df2.loc[df2['length'] == 1, 'kx'].iloc[0] * df2.loc[df2['length'] == 1, 'ky'].iloc[0] * m_h *m_b
P1 = W1 * 50

W2 = S2 * df2.loc[df2['length'] == 0, 'kx'].iloc[0] * df2.loc[df2['length'] == 0, 'ky'].iloc[0] * m_h *m_b
P2 = W2 * 50

#Погрешности
dW1 = (
    df2.loc[df2['length'] == 1, 'kx'].iloc[0] * df2.loc[df2['length'] == 1, 'ky'].iloc[0]
    * sqrt(
        (dS1 * m_h * m_b) ** 2
        + (S1 * m_b * dm_h) ** 2
        + (S1 * m_h * dm_b) ** 2
        )
    )
dW2 = (
    df2.loc[df2['length'] == 0, 'kx'].iloc[0] * df2.loc[df2['length'] == 0, 'ky'].iloc[0]
    * sqrt(
        (dS2 * m_h * m_b) ** 2
        + (S2 * m_b * dm_h) ** 2
        + (S2 * m_h * dm_b) ** 2
        )
    )

dP1 = dW1 * 50
dP2 = dW2 * 50

#Занос значений в таблицу
df2['S'] = np.nan
df2['W'] = np.nan
df2['P'] = np.nan
df2.at[df2[df2['length'] == 1].index[0], 'S'] = S1
df2.at[df2[df2['length'] == 1].index[1], 'S'] = dS1
df2.at[df2[df2['length'] == 0].index[0], 'S'] = S2
df2.at[df2[df2['length'] == 0].index[1], 'S'] = dS2

df2.at[df2[df2['length'] == 1].index[0], 'W'] = W1
df2.at[df2[df2['length'] == 1].index[1], 'W'] = dW1
df2.at[df2[df2['length'] == 0].index[0], 'W'] = W2
df2.at[df2[df2['length'] == 0].index[1], 'W'] = dW2

df2.at[df2[df2['length'] == 1].index[0], 'P'] = P1
df2.at[df2[df2['length'] == 1].index[1], 'P'] = dP1
df2.at[df2[df2['length'] == 0].index[0], 'P'] = P2
df2.at[df2[df2['length'] == 0].index[1], 'P'] = dP2
df2

#Сохранение таблиц

df.to_csv('Results_1.csv')
df2.to_csv('Results_2.csv')

#Построение предельных петель гистерезиса
plt.title('Построение предельных петель гистерезиса')
plt.xlabel('Напряжённость магнитного поля Н, А/м', fontsize=8.)
plt.ylabel('Магнитная индукция B, Тл', fontsize=8.)

plt.xlim(-4000, 4000)
plt.ylim(-1.5, 1.5)

plt.plot(df2.loc[df2['length'] == 1, 'H'], df2.loc[df2['length'] == 1, 'B+'], '-b', marker='o', label='Длинный образец')
plt.plot(df2.loc[df2['length'] == 1, 'H'], df2.loc[df2['length'] == 1, 'B-'], '-b', marker='o')

plt.errorbar(
    df2.loc[df2['length'] == 1, 'H'], df2.loc[df2['length'] == 1, 'B+'],
    df2.loc[df2['length'] == 1, 'B+_error'], df2.loc[df2['length'] == 1, 'H_error'],
    '-b', capsize = 2, linestyle = ''
    )
plt.errorbar(
    df2.loc[df2['length'] == 1, 'H'], df2.loc[df2['length'] == 1, 'B-'],
    df2.loc[df2['length'] == 1, 'B-_error'], df2.loc[df2['length'] == 1, 'H_error'],
    '-b', capsize = 2, linestyle = ''
    )

plt.plot(df2.loc[df2['length'] == 0, 'H'], df2.loc[df2['length'] == 0, 'B+'], '-r', marker='o', label='Короткий образец')
plt.plot(df2.loc[df2['length'] == 0, 'H'], df2.loc[df2['length'] == 0, 'B-'], '-r', marker='o')

plt.errorbar(
    df2.loc[df2['length'] == 0, 'H'], df2.loc[df2['length'] == 0, 'B+'],
    df2.loc[df2['length'] == 0, 'B+_error'], df2.loc[df2['length'] == 0, 'H_error'],
    '-r', capsize = 2, linestyle = ''
    )
plt.errorbar(
    df2.loc[df2['length'] == 0, 'H'], df2.loc[df2['length'] == 0, 'B-'],
    df2.loc[df2['length'] == 0, 'B-_error'], df2.loc[df2['length'] == 0, 'H_error'],
    '-r', capsize = 2, linestyle = ''
    )

plt.grid(axis = 'x')
plt.legend(loc = 'best')
plt.grid(alpha = 0.5)
plt.savefig('Построение_предельных_петель_гистерезиса.png')
plt.show()